services:
  app1:
    image: drakerunner/rinha-de-backend:2023-q3
    depends_on:
      - db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  app2:
    image: drakerunner/rinha-de-backend:2023-q3
    depends_on:
      - db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'


  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - memcached
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
    ulimits:
      nproc: 10000
      nofile:
        soft: 10000
        hard: 10000


  memcached:
    image: memcached:latest
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

    restart: unless-stopped

  db:
    image: postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'

    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret

volumes:
  postgres: